### CREATE
POST http://localhost:8081/api/communications
Content-Type: application/json

{
  "titre": "Réunion pédagogique",
  "typeReunion": "Conseil",
  "date": "2025-01-10",
  "document": "compte_rendu.pdf"
}

### GET ALL
GET http://localhost:8081/api/communications
